name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: make
      run: make

    - name: install perf
      run: |
        sudo apt install perf -y

    - name: set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: run
      run: |
        python scripts/run.py
